App\Entity\Clientes:
    type: entity
    table: clientes
    indexes:
        Clientes_EmpleadosFK:
            columns:
                - CodigoEmpleadoRepVentas
    id:
        codigocliente:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            column: CodigoCliente
            generator:
                strategy: IDENTITY
    fields:
        nombrecliente:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: NombreCliente
        nombrecontacto:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: NombreContacto
        apellidocontacto:
            type: string
            nullable: true
            length: 30
            options:
                fixed: false
            column: ApellidoContacto
        telefono:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: Telefono
        fax:
            type: string
            nullable: false
            length: 15
            options:
                fixed: false
            column: Fax
        lineadireccion1:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: LineaDireccion1
        lineadireccion2:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: LineaDireccion2
        ciudad:
            type: string
            nullable: false
            length: 50
            options:
                fixed: false
            column: Ciudad
        region:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Region
        pais:
            type: string
            nullable: true
            length: 50
            options:
                fixed: false
            column: Pais
        codigopostal:
            type: string
            nullable: true
            length: 10
            options:
                fixed: false
            column: CodigoPostal
        limitecredito:
            type: decimal
            nullable: true
            precision: 15
            scale: 2
            column: LimiteCredito
    manyToOne:
        codigoempleadorepventas:
            targetEntity: Empleados
            cascade: {  }
            fetch: LAZY
            mappedBy: null
            inversedBy: null
            joinColumns:
                CodigoEmpleadoRepVentas:
                    referencedColumnName: CodigoEmpleado
            orphanRemoval: false
    lifecycleCallbacks: {  }
