App\Entity\Usuarios:
    type: entity
    repositoryClass: App\Repository\UsuariosRepository
    table: usuarios
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        login:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        password:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        nombre:
            type: string
            nullable: false
            length: 60
            options:
                fixed: false
        rol:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
        foto:
            type: string
            nullable: false
            length: 20
            options:
                fixed: false
    lifecycleCallbacks: {  }
